### PR TITLE
Add Docker to support older Erlang/Elixir/Node versions

### PR DESCRIPTION
**Pull request by Nezteb**
I wanted to reproduce this demo from your talk in 2019: https://www.youtube.com/watch?v=JvBT4XBdoUE

Unfortunately, both the Erlang and Node versions in the original `.tool-versions` can no longer be installed (easily) on more recent versions of macOS.

Erlang, for example: https://github.com/asdf-vm/asdf-erlang#osx

Current error to debug after upgrading: ~(since there was no `mix.lock` file checked into the repo, the app is pulling the latest versions it can)~
```
==> example_system
Compiling 25 files (.ex)

== Compilation error in file lib/example_system_web/load/view.ex ==
** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Engine.bins_and_vars/3

    The following arguments were given to Phoenix.LiveView.Engine.bins_and_vars/3:

        # 1
        ["\" height=\"500\" class=\"chart\">\n  <style>\n    .title { font-size: 30px;}\n  </style>\n\n  <g transform=\"translate(100, 100)\">\n", "\n    <g stroke=\"black\">\n      <text class=\"title\" text-anchor=\"middle\" dominant-baseline=\"central\" x=\"300\" y=\"-50\" fill=\"black\">\n", {:arg2, [], Phoenix.LiveView.Engine}, "\n      </text>\n    </g>\n", "\n", {:arg3, [], Phoenix.LiveView.Engine}, "\n", "\n    <g stroke-width=\"2\" stroke=\"black\">\n      <line x1=\"0\" x2=\"0\" y1=\"0\" y2=\"", {:arg4, [], Phoenix.LiveView.Engine}, "\"/>\n      <line x1=\"0\" x2=\"", {:arg5, [], Phoenix.LiveView.Engine}, "\" y1=\"", {:arg6, [], Phoenix.LiveView.Engine}, "\" y2=\"", {:arg7, [], Phoenix.LiveView.Engine}, "\"/>\n    </g>\n", "\n    <polyline fill=\"none\" stroke=\"#0074d9\" stroke-width=\"2\" points=\"", {:arg8, [], Phoenix.LiveView.Engine}, "\"/>\n  </g>\n</svg>\n"]

        # 2
        [" ", "<svg viewBox=\"0 0 "]

        # 3
        [{:arg1, [], Phoenix.LiveView.Engine}, {:arg0, [], Phoenix.LiveView.Engine}]

    Attempted function clauses (showing 4 out of 4):

        defp bins_and_vars([bin, var | acc], bins, vars) when is_binary(bin) and is_tuple(var)
        defp bins_and_vars([var | acc], bins, vars) when is_tuple(var)
        defp bins_and_vars([bin], bins, vars) when is_binary(bin)
        defp bins_and_vars([], bins, vars)

    (phoenix_live_view 0.1.0) lib/phoenix_live_view/engine.ex:393: Phoenix.LiveView.Engine.bins_and_vars/3
    (phoenix_live_view 0.1.0) lib/phoenix_live_view/engine.ex:353: Phoenix.LiveView.Engine.to_rendered_struct/3
    (phoenix_live_view 0.1.0) lib/phoenix_live_view/engine.ex:237: Phoenix.LiveView.Engine.handle_body/1
    (phoenix 1.4.2) lib/phoenix/template.ex:349: Phoenix.Template.compile/3
    (phoenix 1.4.2) lib/phoenix/template.ex:160: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.4.2) expanding macro: Phoenix.Template.__before_compile__/1
    lib/example_system_web/load/view.ex:1: ExampleSystemWeb.Load.View (module)
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

When I have more time I'll try to fix the errors to get a minimum replication of the demo app. If you have any insights, please let me know! 😄

### CODE REVIEW

**Comment by Nezteb** [comment]
> Not sure I understand, [mix.lock is committed to the repo](https://github.com/sasa1977/demo_system/blob/master/example_system/mix.lock?rgh-link-date=2023-03-16T08%3A09%3A56Z).

Whoops, disregard. I misread my git diff because the project is in a subdirectory. 🤦‍♂️ 

> Two years ago there was a PR #2 which updated the Elixir, Erlang & other deps. Unfortunately I didn't have the time to look at it then, and the author closed it. I wonder if it would be helpful to reopen it and try to work on top of that, because it brings us much closer to the most recent versions.

Good to know! I'll check out that person's branch and see what I can do!

**Comment by Nezteb** [comment]
@sasa1977 I got things working using Docker. It's a lot simpler, though someday I will hopefully have time to help do a proper upgrade. 😄

**Comment by sasa1977** [comment]
Happy to hear that! However, I don't think I can accept the PR to be merged in this shape, because that means I'd have to maintain both local and the dockerized execution.

**Comment by Nezteb** [comment]
That's totally fair! I'll keep my fork around just in case anyone needs to run the demo in Docker on newer Macs that can't easily run `erlang 21.3.2`/`elixir 1.8.1-otp-21`. If anyone comes asking feel free to link them this PR!

Thanks for making such an awesome talk and demo. 😄

**Pull request closed without merging**
